In [1]:
import hornedchess_1_0 as hc
import numpy as np
from itertools import permutations

print("https://hornedchess.github.io")

https://hornedchess.github.io


In [2]:
hc.N=10
hc.nextMoveDict = hc.genNnextMoveDict(hc.N)
hc.newInitBoard()
hc.struct2img(hc.current_chessboard)

c
|  \
1 -- 2
|  / \
3 -- 4
|  / \
5 -- 6
|  / \
7 -- 8
|  / \
f -- f


In [3]:
hc.cowMoveBestMove()

#Cow 牛
#行一步棋最好的行法
#The best way to make a move
#行動を起こすための最良の方法

hc.struct2img(hc.current_chessboard)

['', 'cow', '', '', '', '', '', '', '', 'farmer', 'farmer']
0
|  \
c -- 2
|  / \
3 -- 4
|  / \
5 -- 6
|  / \
7 -- 8
|  / \
f -- f


In [4]:
hc.farmerMoveBestMove()

#Farmer 農
#行一步棋最好的行法
#The best way to make a move
#行動を起こすための最良の方法

hc.struct2img(hc.current_chessboard)

['', 'cow', '', '', '', '', '', '', 'farmer', 'farmer', '']
0
|  \
c -- 2
|  / \
3 -- 4
|  / \
5 -- 6
|  / \
7 -- f
|  / \
f -- 10


In [5]:
hc.cowCustomMove(1,2)

#行一步棋(自訂的行法)
#A customized way to play a chess move

hc.struct2img(hc.current_chessboard)

['', '', 'cow', '', '', '', '', '', 'farmer', 'farmer', '']
0
|  \
1 -- c
|  / \
3 -- 4
|  / \
5 -- 6
|  / \
7 -- f
|  / \
f -- 10


In [10]:
for x in range(hc.N+1):
    for y in range(hc.N+1):
        for z in range(hc.N+1):
            if x!=y and y!=z and x!=z:
                temp_vector = np.zeros(hc.N+1) - 1
                temp_vector[x] = 0
                temp_vector[y] = temp_vector[z] = 1
                print( temp_vector )

[ 0.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1.]
[ 0.  1. -1. -1.  1. -1. -1. -1. -1. -1. -1.]
[ 0.  1. -1. -1. -1.  1. -1. -1. -1. -1. -1.]
[ 0.  1. -1. -1. -1. -1.  1. -1. -1. -1. -1.]
[ 0.  1. -1. -1. -1. -1. -1.  1. -1. -1. -1.]
[ 0.  1. -1. -1. -1. -1. -1. -1.  1. -1. -1.]
[ 0.  1. -1. -1. -1. -1. -1. -1. -1.  1. -1.]
[ 0.  1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
[ 0.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0. -1.  1.  1. -1. -1. -1. -1. -1. -1. -1.]
[ 0. -1.  1. -1.  1. -1. -1. -1. -1. -1. -1.]
[ 0. -1.  1. -1. -1.  1. -1. -1. -1. -1. -1.]
[ 0. -1.  1. -1. -1. -1.  1. -1. -1. -1. -1.]
[ 0. -1.  1. -1. -1. -1. -1.  1. -1. -1. -1.]
[ 0. -1.  1. -1. -1. -1. -1. -1.  1. -1. -1.]
[ 0. -1.  1. -1. -1. -1. -1. -1. -1.  1. -1.]
[ 0. -1.  1. -1. -1. -1. -1. -1. -1. -1.  1.]
[ 0.  1. -1.  1. -1. -1. -1. -1. -1. -1. -1.]
[ 0. -1.  1.  1. -1. -1. -1. -1. -1. -1. -1.]
[ 0. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1.]
[ 0. -1. -1.  1. -1.  1. -1. -1. -